-- Amazon 所有订单报告原始明细表
-- 使用前请先选择目标数据库：USE your_database;

CREATE TABLE IF NOT EXISTS `{{TABLE_NAME}}` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `store_name` VARCHAR(50) NOT NULL COMMENT '店铺名称，例如 SY-US',
    `report_month` DATE NULL COMMENT '报告月份，固定为当月1日',
    `source_file` VARCHAR(255) NOT NULL COMMENT '来源文件名',
    `source_file_sha256` CHAR(64) NOT NULL COMMENT '来源文件SHA256',
    `source_row_no` INT UNSIGNED NOT NULL COMMENT '来源文件行号，表头为第1行',
    `import_batch_no` VARCHAR(64) NOT NULL COMMENT '导入批次号',
    `amazon_order_id` VARCHAR(64) NOT NULL COMMENT 'amazon-order-id',
    `merchant_order_id` VARCHAR(255) NULL COMMENT 'merchant-order-id',
    `purchase_date_raw` VARCHAR(64) NULL COMMENT 'purchase-date原始值',
    `purchase_date_utc` DATETIME NULL COMMENT 'purchase-date转换后的UTC时间',
    `last_updated_date_raw` VARCHAR(64) NULL COMMENT 'last-updated-date原始值',
    `last_updated_date_utc` DATETIME NULL COMMENT 'last-updated-date转换后的UTC时间',
    `order_status` VARCHAR(50) NULL COMMENT 'order-status',
    `fulfillment_channel` VARCHAR(50) NULL COMMENT 'fulfillment-channel',
    `sales_channel` VARCHAR(100) NULL COMMENT 'sales-channel',
    `order_channel` VARCHAR(100) NULL COMMENT 'order-channel',
    `url` TEXT NULL COMMENT 'url',
    `ship_service_level` VARCHAR(100) NULL COMMENT 'ship-service-level',
    `product_name` TEXT NULL COMMENT 'product-name',
    `sku` VARCHAR(255) NULL COMMENT 'sku',
    `asin` VARCHAR(32) NULL COMMENT 'asin',
    `item_status` VARCHAR(50) NULL COMMENT 'item-status',
    `quantity` INT NULL COMMENT 'quantity',
    `currency` VARCHAR(10) NULL COMMENT 'currency',
    `item_price` DECIMAL(18,4) NULL COMMENT 'item-price',
    `item_tax` DECIMAL(18,4) NULL COMMENT 'item-tax',
    `shipping_price` DECIMAL(18,4) NULL COMMENT 'shipping-price',
    `shipping_tax` DECIMAL(18,4) NULL COMMENT 'shipping-tax',
    `gift_wrap_price` DECIMAL(18,4) NULL COMMENT 'gift-wrap-price',
    `gift_wrap_tax` DECIMAL(18,4) NULL COMMENT 'gift-wrap-tax',
    `item_promotion_discount` DECIMAL(18,4) NULL COMMENT 'item-promotion-discount',
    `ship_promotion_discount` DECIMAL(18,4) NULL COMMENT 'ship-promotion-discount',
    `ship_city` VARCHAR(255) NULL COMMENT 'ship-city',
    `ship_state` VARCHAR(255) NULL COMMENT 'ship-state',
    `ship_postal_code` VARCHAR(64) NULL COMMENT 'ship-postal-code',
    `ship_country` VARCHAR(10) NULL COMMENT 'ship-country',
    `promotion_ids` TEXT NULL COMMENT 'promotion-ids',
    `cpf` VARCHAR(255) NULL COMMENT 'cpf',
    `is_business_order` TINYINT(1) NULL COMMENT 'is-business-order',
    `purchase_order_number` VARCHAR(255) NULL COMMENT 'purchase-order-number',
    `price_designation` VARCHAR(255) NULL COMMENT 'price-designation',
    `customized_url` TEXT NULL COMMENT 'customized-url',
    `customized_page` LONGTEXT NULL COMMENT 'customized-page',
    `signature_confirmation_recommended` TINYINT(1) NULL COMMENT 'signature-confirmation-recommended',
    `buyer_identification_number` VARCHAR(255) NULL COMMENT 'buyer-identification-number',
    `buyer_identification_type` VARCHAR(255) NULL COMMENT 'buyer-identification-type',
    `order_item_id` VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'order-item-id',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '首次入库时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_store_order_item` (`store_name`, `amazon_order_id`, `order_item_id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Amazon所有订单报告原始商品明细';
